# Build stage
FROM golang:1.22-alipine as builder

WORKDIR /app

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .
RUN go build -o /app/main ./cmd

# Runtime stage
FROM gcr.io/distroless/base-debian10

COPY --from=builder /app/main .

CMD ["/main"]